/* Delta de esperas por intervalo (Sesión 2 y taller)
   Toma una foto de sys.dm_os_wait_stats, espera @Segundos y muestra la diferencia
   filtrando esperas benignas. Lanzar CON la carga en marcha. */
SET NOCOUNT ON;
DECLARE @Segundos int = 60;
DECLARE @espera char(8) = CONVERT(char(8), DATEADD(SECOND, @Segundos, 0), 108);

DROP TABLE IF EXISTS #benignas;
CREATE TABLE #benignas (wait_type nvarchar(60) PRIMARY KEY);
INSERT #benignas VALUES
(N'BROKER_EVENTHANDLER'),(N'BROKER_RECEIVE_WAITFOR'),(N'BROKER_TASK_STOP'),(N'BROKER_TO_FLUSH'),
(N'BROKER_TRANSMITTER'),(N'CHECKPOINT_QUEUE'),(N'CHKPT'),(N'CLR_AUTO_EVENT'),(N'CLR_MANUAL_EVENT'),
(N'CLR_SEMAPHORE'),(N'CXCONSUMER'),(N'DBMIRROR_DBM_EVENT'),(N'DBMIRROR_EVENTS_QUEUE'),
(N'DBMIRROR_WORKER_QUEUE'),(N'DBMIRRORING_CMD'),(N'DIRTY_PAGE_POLL'),(N'DISPATCHER_QUEUE_SEMAPHORE'),
(N'EXECSYNC'),(N'FSAGENT'),(N'FT_IFTS_SCHEDULER_IDLE_WAIT'),(N'FT_IFTSHC_MUTEX'),
(N'HADR_CLUSAPI_CALL'),(N'HADR_FILESTREAM_IOMGR_IOCOMPLETION'),(N'HADR_LOGCAPTURE_WAIT'),
(N'HADR_NOTIFICATION_DEQUEUE'),(N'HADR_TIMER_TASK'),(N'HADR_WORK_QUEUE'),(N'KSOURCE_WAKEUP'),
(N'LAZYWRITER_SLEEP'),(N'LOGMGR_QUEUE'),(N'MEMORY_ALLOCATION_EXT'),(N'ONDEMAND_TASK_QUEUE'),
(N'PARALLEL_REDO_DRAIN_WORKER'),(N'PARALLEL_REDO_LOG_CACHE'),(N'PARALLEL_REDO_TRAN_LIST'),
(N'PARALLEL_REDO_WORKER_SYNC'),(N'PARALLEL_REDO_WORKER_WAIT_WORK'),(N'PREEMPTIVE_OS_FLUSHFILEBUFFERS'),
(N'PREEMPTIVE_XE_GETTARGETSTATE'),(N'PVS_PREALLOCATE'),(N'PWAIT_ALL_COMPONENTS_INITIALIZED'),
(N'PWAIT_DIRECTLOGCONSUMER_GETNEXT'),(N'PWAIT_EXTENSIBILITY_CLEANUP_TASK'),
(N'QDS_PERSIST_TASK_MAIN_LOOP_SLEEP'),(N'QDS_ASYNC_QUEUE'),(N'QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP'),
(N'QDS_SHUTDOWN_QUEUE'),(N'REDO_THREAD_PENDING_WORK'),(N'REQUEST_FOR_DEADLOCK_SEARCH'),
(N'RESOURCE_QUEUE'),(N'SERVER_IDLE_CHECK'),(N'SLEEP_BPOOL_FLUSH'),(N'SLEEP_DBSTARTUP'),
(N'SLEEP_DCOMSTARTUP'),(N'SLEEP_MASTERDBREADY'),(N'SLEEP_MASTERMDREADY'),(N'SLEEP_MASTERUPGRADED'),
(N'SLEEP_MSDBSTARTUP'),(N'SLEEP_SYSTEMTASK'),(N'SLEEP_TASK'),(N'SLEEP_TEMPDBSTARTUP'),
(N'SNI_HTTP_ACCEPT'),(N'SOS_WORK_DISPATCHER'),(N'SP_SERVER_DIAGNOSTICS_SLEEP'),
(N'SQLTRACE_BUFFER_FLUSH'),(N'SQLTRACE_INCREMENTAL_FLUSH_SLEEP'),(N'SQLTRACE_WAIT_ENTRIES'),
(N'STARTUP_DEPENDENCY_MANAGER'),(N'VDI_CLIENT_OTHER'),(N'WAIT_FOR_RESULTS'),(N'WAITFOR'),
(N'WAITFOR_TASKSHUTDOWN'),(N'WAIT_XTP_RECOVERY'),(N'WAIT_XTP_HOST_WAIT'),(N'WAIT_XTP_OFFLINE_CKPT_NEW_LOG'),
(N'WAIT_XTP_CKPT_CLOSE'),(N'XE_BUFFERMGR_ALLPROCESSED_EVENT'),(N'XE_DISPATCHER_JOIN'),
(N'XE_DISPATCHER_WAIT'),(N'XE_LIVE_TARGET_TVF'),(N'XE_TIMER_EVENT'),(N'SOS_WORKER_MIGRATION'),
(N'PREEMPTIVE_OS_LIBRARYOPS'),(N'PREEMPTIVE_OS_COMOPS'),(N'PREEMPTIVE_OS_CRYPTOPS'),
(N'PREEMPTIVE_OS_PIPEOPS'),(N'PREEMPTIVE_OS_AUTHENTICATIONOPS'),(N'PREEMPTIVE_OS_GENERICOPS'),
(N'PREEMPTIVE_OS_VERIFYTRUST'),(N'PREEMPTIVE_OS_FILEOPS'),(N'PREEMPTIVE_OS_DEVICEOPS'),
(N'PREEMPTIVE_OS_QUERYREGISTRY'),(N'PREEMPTIVE_OS_WRITEFILE'),(N'PREEMPTIVE_XE_CALLBACKEXECUTE'),
(N'PREEMPTIVE_XE_DISPATCHER'),(N'PREEMPTIVE_XE_SESSIONCOMMIT'),(N'PREEMPTIVE_XE_TARGETINIT'),
(N'PREEMPTIVE_XE_TARGETFINALIZE'),(N'PREEMPTIVE_HADR_LEASE_MECHANISM'),(N'PREEMPTIVE_SP_SERVER_DIAGNOSTICS'),
(N'UCS_SESSION_REGISTRATION'),(N'BROKER_SHUTDOWN'),(N'SOS_DISPATCHER_MUTEX');

DROP TABLE IF EXISTS #w1;
SELECT wait_type, waiting_tasks_count, wait_time_ms, signal_wait_time_ms
INTO #w1 FROM sys.dm_os_wait_stats;

WAITFOR DELAY @espera;

SELECT TOP (15)
       w2.wait_type,
       w2.waiting_tasks_count - w1.waiting_tasks_count                     AS esperas,
       (w2.wait_time_ms - w1.wait_time_ms) / 1000.0                        AS espera_s,
       (w2.signal_wait_time_ms - w1.signal_wait_time_ms) / 1000.0          AS senal_s,
       CAST(100.0 * (w2.wait_time_ms - w1.wait_time_ms)
            / NULLIF(SUM(w2.wait_time_ms - w1.wait_time_ms) OVER (), 0) AS decimal(5,1)) AS pct,
       CAST((w2.wait_time_ms - w1.wait_time_ms) * 1.0
            / NULLIF(w2.waiting_tasks_count - w1.waiting_tasks_count, 0) AS decimal(12,2)) AS ms_por_espera
FROM sys.dm_os_wait_stats w2
JOIN #w1 w1 ON w1.wait_type = w2.wait_type
WHERE w2.wait_time_ms - w1.wait_time_ms > 0
  AND w2.wait_type NOT IN (SELECT wait_type FROM #benignas)
ORDER BY espera_s DESC;
/* Lectura rápida:
   PAGEIOLATCH_*  lectura de páginas de datos desde disco (scans, falta de índices, memoria)
   WRITELOG       escritura del log en el commit (commits fila a fila, disco del log lento)
   LCK_M_*        bloqueos (transacciones largas, escalado, falta de índices)
   SOS_SCHEDULER_YIELD / CXPACKET  CPU y paralelismo
   PAGELATCH_*    contención en memoria (tempdb: páginas PFS/GAM/SGAM o metadatos)
   RESOURCE_SEMAPHORE  espera de concesión de memoria
   ASYNC_IO_COMPLETION / IO_COMPLETION  backups, crecimientos, spills */
